# Generated by Django 4.2.2 on 2023-07-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoryproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical category product', 'verbose_name_plural': 'historical category products'},
        ),
        migrations.AlterModelOptions(
            name='historicalindicator',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical indicator', 'verbose_name_plural': 'historical indicators'},
        ),
        migrations.AlterModelOptions(
            name='historicalmeasureunit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical measure unit', 'verbose_name_plural': 'historical measure units'},
        ),
        migrations.AlterModelOptions(
            name='historicalproducts',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical products', 'verbose_name_plural': 'historical productss'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='measureunit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
