# Generated by Django 4.2.2 on 2023-07-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_categoryproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Categoria de producto', 'verbose_name_plural': 'Categoria de productos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoryproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Categoria de producto', 'verbose_name_plural': 'historical Categoria de productos'},
        ),
        migrations.AlterModelOptions(
            name='historicalindicator',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Indicador de oferta', 'verbose_name_plural': 'historical Indicador de ofertas'},
        ),
        migrations.AlterModelOptions(
            name='historicalmeasureunit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Unidad de Medida', 'verbose_name_plural': 'historical Unidades de Medidas'},
        ),
        migrations.AlterModelOptions(
            name='historicalproducts',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Producto', 'verbose_name_plural': 'historical Productos'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicador de oferta', 'verbose_name_plural': 'Indicador de ofertas'},
        ),
        migrations.AlterModelOptions(
            name='measureunit',
            options={'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medidas'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='categoryproduct',
            name='mesureUnit',
        ),
        migrations.RemoveField(
            model_name='historicalcategoryproduct',
            name='mesureUnit',
        ),
        migrations.AddField(
            model_name='historicalproducts',
            name='categoryProduct',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='Categoria de producto'),
        ),
        migrations.AddField(
            model_name='historicalproducts',
            name='mesureUnit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit', verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='products',
            name='categoryProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Categoria de producto'),
        ),
        migrations.AddField(
            model_name='products',
            name='mesureUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unidad de medida'),
        ),
    ]
